Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,40 +1,44 @@
 name: Build Android APK
-on: [push, pull_request, workflow_dispatch]
+
+on:
+  push:
+    branches: [ "main" ]
+  workflow_dispatch:
 
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
+    - name: Checkout Code
+      uses: actions/checkout@v4
+      with:
+        submodules: recursive
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '17'
+    - name: Set up JDK 17
+      uses: actions/setup-java@v4
+      with:
+        distribution: 'temurin'
+        java-version: '17'
 
-      - name: Setup Android SDK
-        uses: android-actions/setup-android@v3
+    - name: Setup Android SDK
+      uses: android-actions/setup-android@v3
 
-      - name: Make Gradle Executable
-        run: find . -name "gradlew" -exec chmod +x {} \;
+    - name: Make Gradle Executable
+      run: find . -name "gradlew" -exec chmod +x {} \;
 
+    - name: Build APK
+      run: |
+        ANDROID_DIR=$(find . -name "build.gradle" -print -quit | xargs dirname)
+        if [ -z "$ANDROID_DIR" ]; then
+          echo "Android project directory not found!" && exit 1
+        fi
+        cd "$ANDROID_DIR"
+        gradle wrapper
+        ./gradlew assembleDebug
 
-      - name: Build APK
-        run: |
-         GRADLE_PATH=$(find . -name "gradlew" -print -quit)
-         if [ -z "$GRADLE_PATH" ]; then
-           echo "Gradlew file not found!" && exit 1
-         fi
-         cd $(dirname "$GRADLE_PATH")
-         ./gradlew assembleDebug
-
-
-      - name: Upload APK
-        uses: actions/upload-artifact@v4
-        with:
-          name: Strato-Experimental-APK
-          path: app/build/outputs/apk/debug/*.apk
+    - name: Upload APK
+      uses: actions/upload-artifact@v4
+      with:
+        name: Strato-Experimental-APK
+        path: "**/build/outputs/apk/debug/*.apk"
